import { compile } from "@mdx-js/mdx";
import matter from "gray-matter";
import remarkGfm from "remark-gfm";

/** Compile post body to a `.tsx` module string (default export = MDXContent). */
export async function compilePostToTsx(raw: string): Promise<string> {
  const { content } = matter(raw);
  const compiled = await compile(content.trim(), {
    jsxImportSource: "react",
    remarkPlugins: [remarkGfm],
  });

  return `/** Generated by @khoralabs/blog — do not edit. */
// @ts-nocheck
${compiled.value}
`;
}
