import fs from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { parseFrontmatter } from "../posts";
import { compilePostToTsx } from "./compile-post";
import { loadPostFiles } from "./load-post-files";

export type GenerateManifestOptions = {
  postsDir: string;
  outFile: string;
  /** Directory containing `outFile`, used to compute relative import paths. */
  manifestDir?: string;
};

function toPosix(p: string): string {
  return p.split(path.sep).join("/");
}

function relativeImport(fromDir: string, targetPath: string): string {
  let rel = toPosix(path.relative(fromDir, targetPath));
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

export async function generateManifest(options: GenerateManifestOptions): Promise<void> {
  const { postsDir, outFile } = options;
  const manifestDir = options.manifestDir ?? path.dirname(outFile);
  const postsOutDir = path.join(manifestDir, "posts");
  const entries = await loadPostFiles(postsDir);

  await fs.mkdir(postsOutDir, { recursive: true });

  if (entries.length === 0) {
    const empty = `/** Generated by @khoralabs/blog — do not edit. */
import type { BlogPost } from "@khoralabs/blog";

export const blogPosts: BlogPost[] = [];
`;
    await fs.writeFile(outFile, empty, "utf8");
    return;
  }

  const allMetas = await Promise.all(
    entries.map(async (e) => {
      const raw = await fs.readFile(e.filePath, "utf8");
      const { data } = matter(raw);
      const frontmatter = parseFrontmatter(e.slug, data as Record<string, unknown>);
      if (frontmatter.draft) return null;
      const tsx = await compilePostToTsx(raw);
      const tsxPath = path.join(postsOutDir, `${e.slug}.tsx`);
      await fs.writeFile(tsxPath, tsx, "utf8");
      return { entry: e, frontmatter, tsxPath };
    }),
  );
  const metas = allMetas.filter((m) => m !== null);

  const imports = metas
    .map(({ tsxPath }, i) => {
      const importPath = relativeImport(manifestDir, tsxPath);
      return `import post${i} from "${importPath}";`;
    })
    .join("\n");

  const items = metas
    .map(({ entry, frontmatter }, i) => {
      return `  {
    slug: ${JSON.stringify(entry.slug)},
    title: ${JSON.stringify(frontmatter.title)},
    date: ${JSON.stringify(frontmatter.date)},
    author: ${JSON.stringify(frontmatter.author)},
    tags: ${JSON.stringify(frontmatter.tags)},
    description: ${JSON.stringify(frontmatter.description)},
    cover: ${JSON.stringify(frontmatter.cover)},
    Content: post${i},
  }`;
    })
    .join(",\n");

  const body = `/** Generated by @khoralabs/blog — do not edit. */
import type { BlogPost } from "@khoralabs/blog";
import { sortPostsByDate } from "@khoralabs/blog";

${imports}

const unsorted: BlogPost[] = [
${items},
];

export const blogPosts: BlogPost[] = sortPostsByDate(unsorted);
`;

  await fs.writeFile(outFile, body, "utf8");
}
